name: Build and push docker image to the dockerhub

on:
  push:
    branches:
      - main

jobs: 
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - run: npm test
      
  publish:
    build:
      runs-on: ubuntu-latest
      steps:
        name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            push: true
            tags: user/app:latest